name: stocks-dekho-frontend
version: 0
application:
  version: 1.20 # (optional)
  language: go
  ports:
  - port: 3000
    ingress: true
    ingressPath: /
pre-exec:
  commands:  
  - cmd: date # Print the deploy date
